os:
  - linux
language: nix
nix: 2.3.6
before_install:
  - nix-env -iA nixpkgs.cachix
  - echo "trusted-users = root travis" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
  - cachix use maker
  - cachix use dapp
script:
  - nix-shell --pure --argstr url ${ETH_RPC_URL} --run 'dapp test -v --rpc'
